#!/bin/bash

ZLIB='https://www.zlib.net/zlib-1.3.1.tar.gz'
EXPAT='https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.bz2'
C_ARES='https://c-ares.org/download/c-ares-1.28.1.tar.gz'
OPENSSL='https://www.openssl.org/source/openssl-1.1.1w.tar.gz'
LIBRESSL='https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.9.1.tar.gz'
SQLITE3='https://www.sqlite.org/2024/sqlite-autoconf-3450200.tar.gz'
LIBSSH2='https://libssh2.org/download/libssh2-1.11.0.tar.gz'
LIBGMP='https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz'
JEMALLOC='https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2'
